### ISSUE TITLE
Problems with Import

### ISSUE THREAD

**Issue by Spidey0o0AZheng** [zashwood/glm-hmm#3]
Hi Zoe, I am currently in NeuroMatch Academy Summer School 2022, your paper is selected as the project template. Our team are trying to replicate your work for practice and to use these data to make some different analysis. But we soon had some problems at the beginning.

1. We cannot execute `from oneibl.onelight import ONE`. There will be error such as `ModuleNotFoundError: No module named 'oneibl'`, then we try to install some package like `ibllib`, `ONE-api`, but none of that works. Then I found the API of `oneibl` on the  [IBL Library.](https://int-brain-lab.github.io/iblenv/_autosummary/oneibl.onelight.html) But it is strange that when I return to the [API Reference](https://int-brain-lab.github.io/iblenv/010_api_reference.html) column, the information of oneibl is gone. It seems that they no longer provide the official package of oneibl. I cannot install oneibl through the command`pip3 install oneibl`.
2. Then I found a package called [ONE](https://github.com/int-brain-lab/ONE), and I changed all the `from oneibl.onelight import ONE` to `from one.api import ONE`, but the result shows that many packages cannot be found. Obviously, this cannot replace the function of `oneibl`.

Can you help us to get the `oneibl` package? We will really appreciate if you can help us with those problems!

**Comment by zashwood** [comment]
To me this sounds like a versioning issue with `ibllib`.  Can you confirm that you have activated the `glmhmm` environment, and that the version of `ibllib` that you are using is 1.4.14?  Version 1.4.14 of `ibllib` contains `oneibl` (see https://pypi.org/project/ibllib/1.4.14/) while newer versions don't.

**Comment by Spidey0o0AZheng** [comment]
> To me this sounds like a versioning issue with `ibllib`. Can you confirm that you have activated the `glmhmm` environment, and that the version of `ibllib` that you are using is 1.4.14? Version 1.4.14 of `ibllib` contains `oneibl` (see https://pypi.org/project/ibllib/1.4.14/) while newer versions don't.
It seems that this is indeed the problem! My version is 2.3.13, and there is no error after changing the version. Thank you so much!

**Comment by zashwood** [comment]
Ok, great!  Glad that worked.  Going to close this issue since it seems like this is now resolved.
