### ISSUE TITLE
Global GLM-HMM fitting stops without error messages

### ISSUE THREAD

**Issue by sumiya-kuroda** [zashwood/glm-hmm#4]
Hello.

I am trying to run your code with your example data, but when I run the `2_fit_models/fit_global_glmhmm/1_run_inference_global_fit_ibl.py`, it suddenly stops in a half way through like below.

```
(glmhmm) MYNAME@MYPC:~/glm-hmm-main/2_fit_models/fit_global_glmhmm$ python 1_run_inference_global_fit_ibl.py 
Starting inference with K = 2; Fold = 0; Iter = 0
=== fitting GLM-HMM ========
Converged to LP: -64012.9:  23%|████▌               | 68/300 [02:29<08:29,  2.20s/it]
(glmhmm) MYNAME@MYPC:~/glm-hmm-main/2_fit_models/fit_global_glmhmm$
```

It didn't show any error messages, and I am struggling to identify what the cause of this sudden stop is. The python version I'm using is 3.7.6, (as it should be based on `environment.yml`). Do you have experienced anything similar before, and if you have, could you help me solve this problem?

**Comment by zashwood** [comment]
Hi @sumiya-kuroda Thanks for your message, and interest in using the code!  So I think what is happening is that the consecutive values of train set loglikelihood, at iterations 67 and 68, are not sufficiently different and, thus, the convergence criterion at https://github.com/zashwood/ssm/blob/master/ssm/hmm.py#L468-L472 is triggered. 
 This is actually the desired behavior - 300 EM iterations is the absolute _maximum_ number of iterations that should be run, and should not be run for every dataset.  I do think that the printed messages could be clearer so as to convey this better - feel free to submit a PR if you have a suggestion for how to improve printed message.
