### ISSUE TITLE
Possibility of fitting model with obs_dim = 2

### ISSUE THREAD

**Issue by cbimbo** [zashwood/glm-hmm#5]
Hello,

I've been trying to fit your glm-hmm to our behavioural data. It works great, thanks a lot for releasing it! I found the [Jupyter Notebook](https://github.com/zashwood/ssm/blob/master/notebooks/2b%20Input%20Driven%20Observations%20(GLM-HMM).ipynb) particularly useful.
I had a quick question about the possibility of modelling more than just the choices (e.g., as you mention in this Notebook, the reaction time). When I try to do that, I get an error ("InputDrivenObservations written for D = 1!") which seems to mean that it hasn't been implemented yet, so my question is: is there any way, that I missed, to fit a model with obs_dim = 2? If not, is it something you plan to add anytime soon?

Thanks a lot!
Best,
Celian

**Comment by zashwood** [comment]
Hi Celian!  Thanks for your message!  Unfortunately, you are correct that the code is currently only set up to handle obs_dim = 1.  I don't think it would be that hard to modify the observation class to handle obs_dim > 1 in the associated code (https://github.com/zashwood/ssm/blob/master/ssm/observations.py#L695-L801) but this is not something that I currently have the bandwidth to do unfortunately.

**Comment by cbimbo** [comment]
Hi Zoe! Thanks a lot for your super quick reply. I'll try to see what I can do! Cheers.
