### ISSUE TITLE
loop over folds in 1_run_inference_global_fit_ibl.py?

### ISSUE THREAD

**Issue by anhknguyen96** [zashwood/glm-hmm#6]
Hi,

In the 2_apply_post_processing.py script, running return_glmhmm_nll https://github.com/zashwood/glm-hmm/blob/9731b0e45fb0e9dbef6f72187de915fe0005523d/2_fit_models/fit_global_glmhmm/2_apply_post_processing.py#L78 requires multiple fold directories, which is an output of 1_run_inference_global_fit_ibl.py. However, in there fold number is only initialized once https://github.com/zashwood/glm-hmm/blob/9731b0e45fb0e9dbef6f72187de915fe0005523d/2_fit_models/fit_global_glmhmm/1_run_inference_global_fit_ibl.py#L32 (fold==0), and so only one fold_0 directory is returned from the script. Could you please clarify? Should fold be looped over range(num_folds), as in 1_fit_glm_all_ibl_animals_together.py? Thanks.

**Comment by anhknguyen96** [comment]
I think I misunderstood the implementation of script 1_run_inference_global_fit_ibl.py. It's supposed to be run from terminal and z is looped over the range of cluster_arr.shape[0] (==400)?

**Comment by zashwood** [comment]
Hi @anhknguyen96, Thanks for your interest in this code.  Yes, you're exactly correct.  The script is meant to be run on a compute cluster and `z` is meant to range between 0 and zcluster_arr.shape[0]`, which, if you use [this script](https://github.com/zashwood/glm-hmm/blob/main/2_fit_models/fit_global_glmhmm/0_create_cluster_job_arr.py) will, indeed, be 400.  I should probably make this clearer with a comment or in the README.
